# Generated by Django 3.0.2 on 2020-07-24 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
                ('details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('GST', models.CharField(default='', max_length=20)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('job_name', models.CharField(max_length=50)),
                ('job_profile', models.TextField()),
                ('job_salary', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('Job_summary', models.TextField(default='abc')),
                ('job_responsibilities', models.TextField(default='abc')),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Key_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('name_candidate', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Portfolio', models.ImageField(blank=True, upload_to='account/%Y/%m/%d')),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.City')),
                ('education', models.ManyToManyField(blank=True, to='account.Education')),
                ('job_expriance', models.ManyToManyField(blank=True, to='account.Job')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.State')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Job_category'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_keyskills',
            field=models.ManyToManyField(default='COMPUTER', to='account.Key_skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Job_type'),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.State'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Company_type'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.State'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.City'),
        ),
    ]
