# Generated by Django 3.0.2 on 2020-08-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200809_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='home_town',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='sex',
        ),
    ]
