# Generated by Django 3.0.2 on 2020-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200809_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='body',
            field=models.CharField(choices=[('SLIM', 'SLIM'), ('AVG', 'AVG')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='bust',
            field=models.CharField(default='29', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='color',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='complexion',
            field=models.CharField(choices=[('fair', 'fair'), ('dark', 'dark')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='eyes',
            field=models.CharField(choices=[('black', 'black'), ('dark brown', 'dark brown')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='hair_color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='hair_length',
            field=models.CharField(choices=[('long', 'long'), ('short', 'short')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='hips',
            field=models.CharField(default='30', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('gujarati', 'gujarati')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='passport',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='shoe_size',
            field=models.CharField(default='6', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='waist',
            field=models.CharField(default='27', max_length=30),
        ),
    ]
