# Generated by Django 3.0.2 on 2020-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='current_city',
            field=models.CharField(choices=[('SURAT', 'SURAT'), ('ANAND', 'ANAND')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='home_town',
            field=models.CharField(choices=[('SURAT', 'SURAT'), ('ANAND', 'ANAND')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO')], default='1', max_length=30),
        ),
        migrations.DeleteModel(
            name='Company_type',
        ),
    ]
