# Generated by Django 3.0.2 on 2020-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200812_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='Portfolio',
            field=models.ImageField(blank=True, upload_to='account/'),
        ),
    ]
