# Generated by Django 3.0.2 on 2020-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200812_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='portfolio_img1',
            field=models.ImageField(blank=True, upload_to='account/'),
        ),
    ]
