# Generated by Django 3.0.2 on 2020-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_talent_portfolio_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='portfolio_img2',
            field=models.ImageField(blank=True, upload_to='account/'),
        ),
        migrations.AddField(
            model_name='talent',
            name='portfolio_img3',
            field=models.ImageField(blank=True, upload_to='account/'),
        ),
        migrations.AddField(
            model_name='talent',
            name='portfolio_img4',
            field=models.ImageField(blank=True, upload_to='account/'),
        ),
    ]
