# Generated by Django 3.0.2 on 2020-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_talent_about_myself'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='expriance_in_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='about_myself',
            field=models.TextField(default=False, max_length=300),
        ),
    ]
