# Generated by Django 3.0.2 on 2020-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200812_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='about_myself',
            field=models.TextField(max_length=300),
        ),
    ]
