# Generated by Django 3.0.2 on 2020-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200812_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='agency_signed',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='talent',
            name='exprienced',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='1', max_length=30),
        ),
    ]
