# Generated by Django 3.0.2 on 2020-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200821_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='talent',
            name='language',
        ),
        migrations.AddField(
            model_name='talent',
            name='language',
            field=models.ManyToManyField(to='account.Langu'),
        ),
    ]
