# Generated by Django 3.0.2 on 2020-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200821_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='language',
        ),
        migrations.AddField(
            model_name='talent',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('gujarati', 'gujarati')], default='1', max_length=30),
        ),
    ]
